### ISSUE TITLE
java.lang.IllegalStateException: You must provide a WeekViewLoader

### ISSUE THREAD

**Issue by hugothomaz** [jlurena/revolvingweekview#2]
When I try to compile my project using the lib the error:

java.lang.IllegalStateException: You must provide a WeekViewLoader

**Comment by jlurena** [comment]
Hi, this is as expected. You need to provide a WeekViewLoader to render the calendar. Please read the README for more details.

**Comment by hugothomaz** [comment]
Does the lib load the week?
If I want to load the month or two months it is possible because WeekViewEvent receives a DayTime that only has day, hour and minute.
That's right?

**Comment by jlurena** [comment]
It's a static week view, Eg repeating events throughout a week so you'll only be able to load a List of DayTime

**Comment by jlurena** [comment]
Closed as non-issue
