### ISSUE TITLE
How to new event?

### ISSUE THREAD

**Issue by VuPhan99** [jlurena/revolvingweekview#3]

**Comment by jlurena** [comment]
What is your question?

**Comment by kaushikbhut** [comment]
@jlurena 
How to add new event dynamically.
Also, what should I do for a tap on a particular date to get that particular event display?

**Comment by MohamedAssemAli** [comment]
@kaushikbhut 
call `mWeekView.notifyDatasetChanged();
`

**Comment by jlurena** [comment]
> @jlurena
> How to add new event dynamically.
> Also, what should I do for a tap on a particular date to get that particular event display?

Is your issue resolved?
