### ISSUE TITLE
is it possible to adjust the width of the new event in the day view?

### ISSUE THREAD

**Issue by MilanMalovic** [jlurena/revolvingweekview#8]
Hello, i use this library in my project and I should show three events at start table, and it should be very small width. Is it possible to resize a single event width? In the screenshot you can see what it should look like. Thanks
![Screenshot_1324](https://user-images.githubusercontent.com/34768038/95685323-6ab4e600-0bf7-11eb-978a-c83e7ac9112a.png)

**Comment by MilanMalovic** [comment]
@jlurena

**Comment by jlurena** [comment]
> Hello, i use this library in my project and I should show three events at start table, and it should be very small width. Is it possible to resize a single event width? In the screenshot you can see what it should look like. Thanks
> ![Screenshot_1324](https://user-images.githubusercontent.com/34768038/95685323-6ab4e600-0bf7-11eb-978a-c83e7ac9112a.png)

Unfortunately it is not. You're welcome to add a PR that accommodates the sizes.

As a hack, you can potentially just add multiple transparent slots at the same time to slim the visible one down?

**Comment by jlurena** [comment]
Closing this issue as no responds
